### PR TITLE
[WIP] Add empty RFC for authentication

### PR DESCRIPTION
**Pull request by themouette**

### CODE REVIEW

**Comment by themouette** [comment]
@gdchamal oops, I tried to mention you, not assign.

I was wondering: what is the benefit of refresh token + authentication token if both are exposed in the client?

**Comment by gdchamal** [comment]
I added a minimal description of authentication mechanism with python example code. @themouette what can I add to this RFC ?

**Comment by themouette** [comment]
:+1:

**Comment by ziir** [comment]
This involves UX / usability implications that aren't purely technical, i'll ask for feedback in the mailing list.

**Pull request merged**
