### PR TITLE
rfc api message marked as read

### PR DESCRIPTION
**Pull request by iamdey**

### CODE REVIEW

**Comment by gdchamal** [comment]
There will be others update than read messages. Do you think about a specific route for this update or a generic one ?

If second solution the message structure (a list of message) upon a PATCH is not enough

**Comment by iamdey** [comment]
Yes It can be a generic route and yes we would update other things. We won't update certain things so modifiable properties must be specified.

On the other side, we might want to give only one message and the server calculate what previous messages to mark as read as well. I think I prefer the first solution because it is more generic for the API.

**Comment by gdchamal** [comment]
give a list of message for each expected status update on a PATCH

{
    'read': [message1, message2, message3],
    'unread': [message4]
}

**Comment by gdchamal** [comment]
LGTM after last update

**Pull request merged**
